### ISSUE TITLE
trigger timebot only when called

### ISSUE THREAD

**Issue by bnfinet** [caiosba/slack-timezone-converter#1]
instead of having the bot respond to every parsed time it sees it'd be handy to have it interpret times on demand

I'd suggest the trigger be ":time" or "@slacktimebot" or such

I think the proper metaphor for channel bots is "a tool on the shelf".  It's there to help when the humans ask, not to chime in unprompted

**Comment by MZAWeb** [comment]
Our fork does that if you still need it https://github.com/moderntribe/slack-timezone-converter

**Comment by caiosba** [comment]
Nice! Would you mind submitting a pull request?

**Comment by MZAWeb** [comment]
Sure, but note that I didn't do it dynamic. I just added an extra conditional that suits our use case.

**Comment by caiosba** [comment]
Looks good actually.

**Comment by caiosba** [comment]
Merged and fixed.
