### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by tysonstewart** [caiosba/slack-timezone-converter#3]
Thanks for putting this project out there! I can't seem to get it to work, though, and I'd really like to. I set up a bot on Slack and received an error for this line when trying to run your script:
https://github.com/caiosba/slack-timezone-converter/blob/master/slack-timezone-converter.rb#L59

It seems that a newly-created bot has its `tz` property set as `null`. I added a little hack to get around that limitation, but unfortunately the bot still didn't work. I have to give up because I'm out of time. :-/

**Comment by caiosba** [comment]
Glad you liked it! Let's try to put it to work :)

Can you please provide the error exactly?

Also, is `CURRENT_USER` setup?

**Comment by tysonstewart** [comment]
Here's the error it produces:

`slack-timezone-converter.rb:59:in `<main>': undefined method `[]' for nil:NilClass (NoMethodError)`

I tracked it down to the `tz` property being `null` as I mentioned above. Here's the bot user:

```
{
  "ok": true,
  "user": {
    "id": "THINGS",
    "team_id": "THINGS",
    "name": "timezone-converter",
    "deleted": false,
    "status": null,
    "color": "dc7dbb",
    "real_name": "TZ",
    "tz": null,
    "tz_label": "Pacific Standard Time",
    "tz_offset": -28800,
    "profile": {
    ...
```

I couldn't find a way to set that property in Slack, so I added a few lines to work around it. Then I invited the bot into our channel and Slack and posted a time. The bot didn't do anything, which is where I gave up. I'm not sure if it's receiving messages or not, but the script reported that it was connected to Slack.

**Comment by caiosba** [comment]
Humm actually looks like CURRENT_USER is null... can you please paste the output after adding this at line 33: `raise response.body.inspect`

**Comment by tysonstewart** [comment]
`slack-timezone-converter.rb:33:in `<main>': "{\"ok\":true,\"url\":\"https:\\/\\/MY_SITE.slack.com\\/\",\"team\":\"MY_SITE\",\"user\":\"timezone-converter\",\"team_id\":\"MY_SITE_ID\",\"user_id\":\"MY_USER_ID\"}" (RuntimeError)`

(scrubbed)

**Comment by caiosba** [comment]
Yeah the problem is that your user doesn't have `tz` - is it set in "Time Zone" at https://<your domain>.slack.com/account/settings ?

**Comment by tysonstewart** [comment]
Yes, it is for _me_, but not the bot.

**Comment by caiosba** [comment]
Did you try with your user, just to test?

**Comment by tysonstewart** [comment]
I couldn't figure out how to generate a token for my user, which is why I created an integration bot for it.

**Comment by tysonstewart** [comment]
I just got it to respond to a time message. In addition to the hack I mentioned above, I also had to remove this check from the message processing loop: `and data['text'].include?("@time")`.

**Comment by caiosba** [comment]
Oh yes, the messages needs to contain `@time` in order to be converted :)

This is true since I merge #2 :)

Just realized that it's not on the `README`! Sorry, I will add that!
